# Generated by Django 5.0 on 2023-12-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinarists', '0003_alter_experience_options_experience_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
