# Generated by Django 5.0 on 2023-12-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinarists', '0004_meal_allergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='culinarists.meal')),
            ],
        ),
    ]
